# git-cliff ~ configuration
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "0xsysr3ll"
repo = "scroblarr"

[changelog]
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
        {% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message | upper_first }}\
        {% if commit.message is not ending_with(".") and commit.message is not ending_with("!") %}.{% endif %} - \
        ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))
{% endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]\
          ({{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits | filter(attribute="scope") | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {% endfor %}
    {% for commit in commits %}
        {% if not commit.scope %}
        {{ self::print_commit(commit=commit) }}
        {% endif %}
    {% endfor %}
{% endfor %}
{% if github.contributors is defined and github.contributors | length > 0 %}
{% set first_time = github.contributors | filter(attribute="is_first_time", value=true) %}
{% if first_time | length > 0 %}
  ## New Contributors
{% for contributor in first_time %}
  * @{{ contributor.username }} made their first contribution\
    {% if contributor.pr_number %} in [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}){% endif %}
{% endfor %}
{% endif %}
{% endif %}
"""
trim = true
render_always = true
footer = """
<!-- generated by git-cliff -->
"""
postprocessors = [
    { pattern = '<REPO>', replace = "https://github.com/0xsysr3ll/scroblarr" },
]

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
commit_preprocessors = [
    { pattern = '\\((\\w+\\s)?#([0-9]+)\\)', replace = "([#${2}](<REPO>/issues/${2}))" },
]
protect_breaking_commits = false
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Bug Fixes" },
    { message = "^doc", group = "Documentation" },
    { message = "^perf", group = "Performance" },
    { message = "^refactor", group = "Refactor" },
    { message = "^style", group = "Styling" },
    { message = "^test", group = "Testing" },
    { message = "^chore\\(release\\)", skip = true },
    { message = "^chore\\(deps", skip = true },
    { message = "^chore|^ci", group = "Miscellaneous" },
    { body = ".*security", group = "Security" },
    { message = "^revert", group = "Revert" },
    { message = ".*", group = "Other" },
]
filter_commits = false
fail_on_unmatched_commit = false
topo_order_commits = true
sort_commits = "newest"
tag_pattern = "v[0-9].*"
